### ISSUE TITLE
Are you running a workshop?

### ISSUE THREAD

**Issue by rgaiacs** [ManimCommunity/jupyter_examples#18]
Hi,

at the time of writing, I noticed that mybinder.org has 24 users using this repository.

Because [mybinder.org is running with reduced capacity](https://blog.jupyter.org/mybinder-org-reducing-capacity-c93ccfc6413f) and [I'm working to improve one of the mybinder.org servers](https://github.com/jupyterhub/mybinder.org-deploy/issues/3056), I want to check if a workshop using this repository is happening at the time of the writing.

Thanks and all the best with the workshop, if it is happening.

**Comment by behackl** [comment]
Hey there! In case there was any sort of event, we have not been aware of it.

**Comment by rgaiacs** [comment]
Thanks @behackl for the reply.
